Repository pytr-org/pytr, pull requests merged in 2025-02, with the labels that each got.

#171 Enable Renovate
  .github/renovate.json
Labels: enhancement

#153 Fix: Sometimes Value of tax is too large by a factor of 1000 (#141)
  pytr/event.py
  tests/test_parsing.py
Labels: change requested

#157 Increase netSize precision to 6 decimal when exporting portfolio in CSV
  pytr/portfolio.py
Labels: enhancement

#179 Add a `--date-isoformat` option to `pytr export_transactions`
  pytr/event_formatter.py
  pytr/main.py
  pytr/transactions.py
Labels: enhancement

#186 Map `card_tr_refund` transaction to `DEPOSIT`
  pytr/event.py
Labels: bug

#190 Map `PAYMENT_INBOUND_CREDIT_CARD` transaction and parse fees for deposits/removals
  pytr/event.py
  tests/sample_credit_card_deposit.json
  tests/test_event_csv_formatter.py
Labels: enhancement
